version: '3.8'

services:
  user-db:
    image: postgres:latest
    container_name: user-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpassword
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data

  order-db:
    image: postgres:latest
    container_name: order-db
    environment:
      POSTGRES_USER: order
      POSTGRES_PASSWORD: orderpassword
      POSTGRES_DB: orderdb
    ports:
      - "5433:5432"
    volumes:
      - order-db-data:/var/lib/postgresql/data

volumes:
  user-db-data:
  order-db-data: