spring:
  application:
    name: user-service
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: user
    password: userpassword
    driver-class-name: org.postgresql.Driver

server:
  port: 8000

jwt:
  secret: "MIICzTBLBgkqhkiG9w0BBQ0wPjApBgkqhkiG9w0BBQwwHAQI1M8uVZ0qac0CAggA"
  expiration: 1440000  # 1000 * 60 * 24