spring:
  application:
    name: order-service
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5433/orderdb
    username: order
    password: orderpassword
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092

message:
  group: orderGroup
  topic:
    create-user: createUser
    remove-user: removeUser

server:
  port: 8100
